//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Ale\Desktop\Proyecto\Compiler\Logic\Parser\Grammar\coolgrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="coolgrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IcoolgrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="coolgrammarParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] coolgrammarParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="coolgrammarParser.class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass([NotNull] coolgrammarParser.ClassContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>f_attr</c>
	/// labeled alternative in <see cref="coolgrammarParser.feature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitF_attr([NotNull] coolgrammarParser.F_attrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>f_method</c>
	/// labeled alternative in <see cref="coolgrammarParser.feature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitF_method([NotNull] coolgrammarParser.F_methodContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="coolgrammarParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod([NotNull] coolgrammarParser.MethodContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="coolgrammarParser.attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttr([NotNull] coolgrammarParser.AttrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="coolgrammarParser.formal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormal([NotNull] coolgrammarParser.FormalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>body</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody([NotNull] coolgrammarParser.BodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>comp</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComp([NotNull] coolgrammarParser.CompContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>assign</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign([NotNull] coolgrammarParser.AssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>let</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLet([NotNull] coolgrammarParser.LetContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>int</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] coolgrammarParser.IntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>isvoid</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIsvoid([NotNull] coolgrammarParser.IsvoidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>sumaresta</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSumaresta([NotNull] coolgrammarParser.SumarestaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>while</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile([NotNull] coolgrammarParser.WhileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>call_method</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall_method([NotNull] coolgrammarParser.Call_methodContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>id</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] coolgrammarParser.IdContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>new_type</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNew_type([NotNull] coolgrammarParser.New_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multdiv</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultdiv([NotNull] coolgrammarParser.MultdivContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>if</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf([NotNull] coolgrammarParser.IfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unary_exp</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_exp([NotNull] coolgrammarParser.Unary_expContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parentesis</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParentesis([NotNull] coolgrammarParser.ParentesisContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>string</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] coolgrammarParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>dispatch</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDispatch([NotNull] coolgrammarParser.DispatchContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>bool</c>
	/// labeled alternative in <see cref="coolgrammarParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool([NotNull] coolgrammarParser.BoolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="coolgrammarParser.expr_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_list([NotNull] coolgrammarParser.Expr_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="coolgrammarParser.args_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgs_def([NotNull] coolgrammarParser.Args_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="coolgrammarParser.args_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgs_call([NotNull] coolgrammarParser.Args_callContext context);
}
