//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Ale\documents\visual studio 2017\Projects\Compiler\Logic\Parser\Grammar\coolgrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class coolgrammarLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, CLASS=19, INHERITS=20, LET=21, IN=22, WS=23, IF=24, THEN=25, 
		ELSE=26, FI=27, WHILE=28, LOOP=29, POOL=30, NEW=31, TYPE=32, ISVOID=33, 
		INTEGER=34, TRUE=35, FALSE=36, NOT=37, ID=38;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "T__14", "T__15", "T__16", 
		"T__17", "CLASS", "INHERITS", "LET", "IN", "WS", "IF", "THEN", "ELSE", 
		"FI", "WHILE", "LOOP", "POOL", "NEW", "TYPE", "ISVOID", "INTEGER", "TRUE", 
		"FALSE", "NOT", "ID"
	};


	public coolgrammarLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public coolgrammarLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "';'", "'{'", "'}'", "'('", "')'", "':'", "'<-'", "'@'", "'.'", 
		"'*'", "'/'", "'+'", "'-'", "'<'", "'<='", "'='", "'~'", "','", "'class'", 
		"'inherits'", "'let'", "'in'", null, "'if'", "'then'", "'else'", "'fi'", 
		"'while'", "'loop'", "'pool'", "'new'", null, "'isvoid'", null, "'true'", 
		"'false'", "'not'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, "CLASS", "INHERITS", "LET", 
		"IN", "WS", "IF", "THEN", "ELSE", "FI", "WHILE", "LOOP", "POOL", "NEW", 
		"TYPE", "ISVOID", "INTEGER", "TRUE", "FALSE", "NOT", "ID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "coolgrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static coolgrammarLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '(', '\xDF', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', 
		'\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x18', '\x6', '\x18', '\x8D', '\n', '\x18', '\r', '\x18', 
		'\xE', '\x18', '\x8E', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', 
		'\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', 
		'\x1F', '\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', '!', '\x3', 
		'!', '\a', '!', '\xB9', '\n', '!', '\f', '!', '\xE', '!', '\xBC', '\v', 
		'!', '\x3', '\"', '\x3', '\"', '\x3', '\"', '\x3', '\"', '\x3', '\"', 
		'\x3', '\"', '\x3', '\"', '\x3', '#', '\x6', '#', '\xC6', '\n', '#', '\r', 
		'#', '\xE', '#', '\xC7', '\x3', '$', '\x3', '$', '\x3', '$', '\x3', '$', 
		'\x3', '$', '\x3', '%', '\x3', '%', '\x3', '%', '\x3', '%', '\x3', '%', 
		'\x3', '%', '\x3', '&', '\x3', '&', '\x3', '&', '\x3', '&', '\x3', '\'', 
		'\x3', '\'', '\a', '\'', '\xDB', '\n', '\'', '\f', '\'', '\xE', '\'', 
		'\xDE', '\v', '\'', '\x2', '\x2', '(', '\x3', '\x3', '\x5', '\x4', '\a', 
		'\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', 
		'\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', 
		'\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', 
		'\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', 
		'\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', 
		';', '\x1F', '=', ' ', '?', '!', '\x41', '\"', '\x43', '#', '\x45', '$', 
		'G', '%', 'I', '&', 'K', '\'', 'M', '(', '\x3', '\x2', '\a', '\x5', '\x2', 
		'\v', '\f', '\xF', '\xF', '\"', '\"', '\x3', '\x2', '\x43', '\\', '\x6', 
		'\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x3', 
		'\x2', '\x32', ';', '\x3', '\x2', '\x63', '|', '\x2', '\xE2', '\x2', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x2', 
		';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', '\x41', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x43', '\x3', '\x2', '\x2', '\x2', '\x2', '\x45', '\x3', 
		'\x2', '\x2', '\x2', '\x2', 'G', '\x3', '\x2', '\x2', '\x2', '\x2', 'I', 
		'\x3', '\x2', '\x2', '\x2', '\x2', 'K', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'M', '\x3', '\x2', '\x2', '\x2', '\x3', 'O', '\x3', '\x2', '\x2', '\x2', 
		'\x5', 'Q', '\x3', '\x2', '\x2', '\x2', '\a', 'S', '\x3', '\x2', '\x2', 
		'\x2', '\t', 'U', '\x3', '\x2', '\x2', '\x2', '\v', 'W', '\x3', '\x2', 
		'\x2', '\x2', '\r', 'Y', '\x3', '\x2', '\x2', '\x2', '\xF', '[', '\x3', 
		'\x2', '\x2', '\x2', '\x11', '^', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'`', '\x3', '\x2', '\x2', '\x2', '\x15', '\x62', '\x3', '\x2', '\x2', 
		'\x2', '\x17', '\x64', '\x3', '\x2', '\x2', '\x2', '\x19', '\x66', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', 'h', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'j', '\x3', '\x2', '\x2', '\x2', '\x1F', 'l', '\x3', '\x2', '\x2', '\x2', 
		'!', 'o', '\x3', '\x2', '\x2', '\x2', '#', 'q', '\x3', '\x2', '\x2', '\x2', 
		'%', 's', '\x3', '\x2', '\x2', '\x2', '\'', 'u', '\x3', '\x2', '\x2', 
		'\x2', ')', '{', '\x3', '\x2', '\x2', '\x2', '+', '\x84', '\x3', '\x2', 
		'\x2', '\x2', '-', '\x88', '\x3', '\x2', '\x2', '\x2', '/', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '\x31', '\x92', '\x3', '\x2', '\x2', '\x2', '\x33', 
		'\x95', '\x3', '\x2', '\x2', '\x2', '\x35', '\x9A', '\x3', '\x2', '\x2', 
		'\x2', '\x37', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x39', '\xA2', '\x3', 
		'\x2', '\x2', '\x2', ';', '\xA8', '\x3', '\x2', '\x2', '\x2', '=', '\xAD', 
		'\x3', '\x2', '\x2', '\x2', '?', '\xB2', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'\xB6', '\x3', '\x2', '\x2', '\x2', '\x43', '\xBD', '\x3', '\x2', '\x2', 
		'\x2', '\x45', '\xC5', '\x3', '\x2', '\x2', '\x2', 'G', '\xC9', '\x3', 
		'\x2', '\x2', '\x2', 'I', '\xCE', '\x3', '\x2', '\x2', '\x2', 'K', '\xD4', 
		'\x3', '\x2', '\x2', '\x2', 'M', '\xD8', '\x3', '\x2', '\x2', '\x2', 'O', 
		'P', '\a', '=', '\x2', '\x2', 'P', '\x4', '\x3', '\x2', '\x2', '\x2', 
		'Q', 'R', '\a', '}', '\x2', '\x2', 'R', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'S', 'T', '\a', '\x7F', '\x2', '\x2', 'T', '\b', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'V', '\a', '*', '\x2', '\x2', 'V', '\n', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'X', '\a', '+', '\x2', '\x2', 'X', '\f', '\x3', '\x2', '\x2', 
		'\x2', 'Y', 'Z', '\a', '<', '\x2', '\x2', 'Z', '\xE', '\x3', '\x2', '\x2', 
		'\x2', '[', '\\', '\a', '>', '\x2', '\x2', '\\', ']', '\a', '/', '\x2', 
		'\x2', ']', '\x10', '\x3', '\x2', '\x2', '\x2', '^', '_', '\a', '\x42', 
		'\x2', '\x2', '_', '\x12', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\a', 
		'\x30', '\x2', '\x2', '\x61', '\x14', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'\x63', '\a', ',', '\x2', '\x2', '\x63', '\x16', '\x3', '\x2', '\x2', 
		'\x2', '\x64', '\x65', '\a', '\x31', '\x2', '\x2', '\x65', '\x18', '\x3', 
		'\x2', '\x2', '\x2', '\x66', 'g', '\a', '-', '\x2', '\x2', 'g', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', 'h', 'i', '\a', '/', '\x2', '\x2', 'i', '\x1C', 
		'\x3', '\x2', '\x2', '\x2', 'j', 'k', '\a', '>', '\x2', '\x2', 'k', '\x1E', 
		'\x3', '\x2', '\x2', '\x2', 'l', 'm', '\a', '>', '\x2', '\x2', 'm', 'n', 
		'\a', '?', '\x2', '\x2', 'n', ' ', '\x3', '\x2', '\x2', '\x2', 'o', 'p', 
		'\a', '?', '\x2', '\x2', 'p', '\"', '\x3', '\x2', '\x2', '\x2', 'q', 'r', 
		'\a', '\x80', '\x2', '\x2', 'r', '$', '\x3', '\x2', '\x2', '\x2', 's', 
		't', '\a', '.', '\x2', '\x2', 't', '&', '\x3', '\x2', '\x2', '\x2', 'u', 
		'v', '\a', '\x65', '\x2', '\x2', 'v', 'w', '\a', 'n', '\x2', '\x2', 'w', 
		'x', '\a', '\x63', '\x2', '\x2', 'x', 'y', '\a', 'u', '\x2', '\x2', 'y', 
		'z', '\a', 'u', '\x2', '\x2', 'z', '(', '\x3', '\x2', '\x2', '\x2', '{', 
		'|', '\a', 'k', '\x2', '\x2', '|', '}', '\a', 'p', '\x2', '\x2', '}', 
		'~', '\a', 'j', '\x2', '\x2', '~', '\x7F', '\a', 'g', '\x2', '\x2', '\x7F', 
		'\x80', '\a', 't', '\x2', '\x2', '\x80', '\x81', '\a', 'k', '\x2', '\x2', 
		'\x81', '\x82', '\a', 'v', '\x2', '\x2', '\x82', '\x83', '\a', 'u', '\x2', 
		'\x2', '\x83', '*', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\a', 
		'n', '\x2', '\x2', '\x85', '\x86', '\a', 'g', '\x2', '\x2', '\x86', '\x87', 
		'\a', 'v', '\x2', '\x2', '\x87', ',', '\x3', '\x2', '\x2', '\x2', '\x88', 
		'\x89', '\a', 'k', '\x2', '\x2', '\x89', '\x8A', '\a', 'p', '\x2', '\x2', 
		'\x8A', '.', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8D', '\t', '\x2', 
		'\x2', '\x2', '\x8C', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8E', 
		'\x3', '\x2', '\x2', '\x2', '\x8E', '\x8C', '\x3', '\x2', '\x2', '\x2', 
		'\x8E', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', '\x3', '\x2', 
		'\x2', '\x2', '\x90', '\x91', '\b', '\x18', '\x2', '\x2', '\x91', '\x30', 
		'\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\a', 'k', '\x2', '\x2', '\x93', 
		'\x94', '\a', 'h', '\x2', '\x2', '\x94', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\x95', '\x96', '\a', 'v', '\x2', '\x2', '\x96', '\x97', '\a', 
		'j', '\x2', '\x2', '\x97', '\x98', '\a', 'g', '\x2', '\x2', '\x98', '\x99', 
		'\a', 'p', '\x2', '\x2', '\x99', '\x34', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x9B', '\a', 'g', '\x2', '\x2', '\x9B', '\x9C', '\a', 'n', '\x2', '\x2', 
		'\x9C', '\x9D', '\a', 'u', '\x2', '\x2', '\x9D', '\x9E', '\a', 'g', '\x2', 
		'\x2', '\x9E', '\x36', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\a', 
		'h', '\x2', '\x2', '\xA0', '\xA1', '\a', 'k', '\x2', '\x2', '\xA1', '\x38', 
		'\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\a', 'y', '\x2', '\x2', '\xA3', 
		'\xA4', '\a', 'j', '\x2', '\x2', '\xA4', '\xA5', '\a', 'k', '\x2', '\x2', 
		'\xA5', '\xA6', '\a', 'n', '\x2', '\x2', '\xA6', '\xA7', '\a', 'g', '\x2', 
		'\x2', '\xA7', ':', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\a', 
		'n', '\x2', '\x2', '\xA9', '\xAA', '\a', 'q', '\x2', '\x2', '\xAA', '\xAB', 
		'\a', 'q', '\x2', '\x2', '\xAB', '\xAC', '\a', 'r', '\x2', '\x2', '\xAC', 
		'<', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\a', 'r', '\x2', '\x2', 
		'\xAE', '\xAF', '\a', 'q', '\x2', '\x2', '\xAF', '\xB0', '\a', 'q', '\x2', 
		'\x2', '\xB0', '\xB1', '\a', 'n', '\x2', '\x2', '\xB1', '>', '\x3', '\x2', 
		'\x2', '\x2', '\xB2', '\xB3', '\a', 'p', '\x2', '\x2', '\xB3', '\xB4', 
		'\a', 'g', '\x2', '\x2', '\xB4', '\xB5', '\a', 'y', '\x2', '\x2', '\xB5', 
		'@', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xBA', '\t', '\x3', '\x2', '\x2', 
		'\xB7', '\xB9', '\t', '\x4', '\x2', '\x2', '\xB8', '\xB7', '\x3', '\x2', 
		'\x2', '\x2', '\xB9', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xB8', 
		'\x3', '\x2', '\x2', '\x2', '\xBA', '\xBB', '\x3', '\x2', '\x2', '\x2', 
		'\xBB', '\x42', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBA', '\x3', '\x2', 
		'\x2', '\x2', '\xBD', '\xBE', '\a', 'k', '\x2', '\x2', '\xBE', '\xBF', 
		'\a', 'u', '\x2', '\x2', '\xBF', '\xC0', '\a', 'x', '\x2', '\x2', '\xC0', 
		'\xC1', '\a', 'q', '\x2', '\x2', '\xC1', '\xC2', '\a', 'k', '\x2', '\x2', 
		'\xC2', '\xC3', '\a', '\x66', '\x2', '\x2', '\xC3', '\x44', '\x3', '\x2', 
		'\x2', '\x2', '\xC4', '\xC6', '\t', '\x5', '\x2', '\x2', '\xC5', '\xC4', 
		'\x3', '\x2', '\x2', '\x2', '\xC6', '\xC7', '\x3', '\x2', '\x2', '\x2', 
		'\xC7', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xC8', '\x3', '\x2', 
		'\x2', '\x2', '\xC8', '\x46', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xCA', 
		'\a', 'v', '\x2', '\x2', '\xCA', '\xCB', '\a', 't', '\x2', '\x2', '\xCB', 
		'\xCC', '\a', 'w', '\x2', '\x2', '\xCC', '\xCD', '\a', 'g', '\x2', '\x2', 
		'\xCD', 'H', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xCF', '\a', 'h', '\x2', 
		'\x2', '\xCF', '\xD0', '\a', '\x63', '\x2', '\x2', '\xD0', '\xD1', '\a', 
		'n', '\x2', '\x2', '\xD1', '\xD2', '\a', 'u', '\x2', '\x2', '\xD2', '\xD3', 
		'\a', 'g', '\x2', '\x2', '\xD3', 'J', '\x3', '\x2', '\x2', '\x2', '\xD4', 
		'\xD5', '\a', 'p', '\x2', '\x2', '\xD5', '\xD6', '\a', 'q', '\x2', '\x2', 
		'\xD6', '\xD7', '\a', 'v', '\x2', '\x2', '\xD7', 'L', '\x3', '\x2', '\x2', 
		'\x2', '\xD8', '\xDC', '\t', '\x6', '\x2', '\x2', '\xD9', '\xDB', '\t', 
		'\x4', '\x2', '\x2', '\xDA', '\xD9', '\x3', '\x2', '\x2', '\x2', '\xDB', 
		'\xDE', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDA', '\x3', '\x2', '\x2', 
		'\x2', '\xDC', '\xDD', '\x3', '\x2', '\x2', '\x2', '\xDD', 'N', '\x3', 
		'\x2', '\x2', '\x2', '\xDE', '\xDC', '\x3', '\x2', '\x2', '\x2', '\a', 
		'\x2', '\x8E', '\xBA', '\xC7', '\xDC', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
